include $(GOROOT)/src/Make.inc

TARG=github.com/petar/ShelfLife/sociability
GOFILES=\
	api.go\
	enc.go\
	err.go\
	like.go\
	follow.go\
	login.go\
	msg.go\
	pass.go\
	sanitize.go\

include $(GOROOT)/src/Make.pkg
