# Copyright 2011 ShelfLife Authors. All rights reserved.
# Use of this source code is governed by a
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=shelf-server
GOFILES=\
	main.go\

include $(GOROOT)/src/Make.cmd
